sonar.projectKey=TaskManagementTool
sonar.organization=hamzashakeel1221
sonar.projectName=Task Management Tool
sonar.projectVersion=1.0
sonar.sources=backend/TaskManagement.API,frontend/task-ui/src
sonar.tests=backend/TaskManagement.Tests
sonar.exclusions=**/node_modules/**,**/bin/**,**/obj/**,**/Migrations/**
sonar.cs.opencover.reportsPaths=backend/TaskManagement.Tests/coverage.xml